[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "frame-ancestors 'none';"

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/home.html"
  status = 200
